### ISSUE TITLE
Detect duplicate comments

### ISSUE THREAD

**Issue by krafit** [pluginkollektiv/antispam-bee#158]
As noted in [this forum thread](https://wordpress.org/support/topic/option-for-remove-duplicates/), it might be an interesting option, to add an option for automatic duplicate detection.

**Note:** Duplicates are not always ill intended spam, but can also occur due to strange connection errors or rough browsers.

**Comment by websupporter** [comment]
> Not a few messages filtered into my spam folder by mistake. So I have to see the list of spam. Most of these messages are the same. I would like to have in settings the option for automatic deletion of duplicates in the spam folder.
> Of the 1000 messages in my spam folder, there are a few got there by mistake (not spam). However, the unique spam, just 100 messages, the rest were duplicates.

I like this idea. :+1:

**Comment by Zodiac1978** [comment]
If you have missed some updates from ASB your blog can get "flooded" with spam and you need to analyze them manually. So removing duplicates is a great step. A new "Analyze all (pending?) comments" button would be even greater ... which check could be used here? RegEx of course. What about the other checks?

**Comment by websupporter** [comment]
Question to solve:

What qualifies as duplicate?
* Same content
* Same content + same author name
* Same content + same post
* Same content + same email
* Same content + same IP

A combination of above?

**Comment by Zodiac1978** [comment]
Some thoughts:

Same content only could be a problem for small text like "Agreed", "Confirmed", etc.
Same content + same IP wouldn't stop distributed spam attacks from botnets.

I know this would be much more work, but what about a configurable version of this feature. So the user can use same IP (if this is the best solution for the spam for this site) and same post, same email if it is better to use this setting ... What do you think @websupporter ?

**Comment by stklcode** [comment]
> Same content only could be a problem for small text like "Agreed", "Confirmed", etc.
Same Problem for Content + Name...

> [...] what about a configurable version of this feature. So the user can use same IP (if this is the best solution for the spam for this site) and same post, same email if it is better to use this setting ...
I could imagine a list of checkboxes "what to include in duplicate detection".  
I'd also add a word count threshold then to overcome the above problem for short comments. 

If not complex enough yet, probably a time limit in which a duplicate is discarded but not learned in any kind of spam library. This would minimize the risk of penalizing accidental double posts.

**Comment by websupporter** [comment]
Two thoughts, utterly cluttered: Maybe we should not have it "automatic", if this means having it in the process of defining whether to save a comment. The problem described is: I need to go through the spam comments to see, if everything is spam. My problem is, its a huge list, because of duplicates. I would like to have an option to remove duplicates... What about a button in the spam view "Delete duplicates".

_Why a button?_
* First of all, it does not add yet another option to the cluttered settings page :laughing: 
* The problem is not really related to defining whether a comment is spam or not, but to "managing spam manually in the spam folder"
* Lets say you go full options, for every comment coming in, you call two apis, not quite sure how many database lookups and now, after you have decided it is spam, you need yet another db lookup just to make sure, you do not have this comment saved already. I do not have a problem with spammers waiting for a response, but its still computing time involved. And its for a task, which is not really about "is this spam?"

The contra to a button is in my opinion the extra click. So, if we weigh for automatic, then I would think of it as a cron job with all its downsides; hence the button.

_Decision or option_
I think we should come forward with what a duplicate is and see the feedback. I think its definitely something which would evolve over time, but we should give it a starting point. For me at the moment the most reasonable definition would be "same content + (same email or ip) + same post".

I would like to come up with our own definition of "what is duplicate", because I am a bit opposed to all this options stuff in ASB. I think of this definition like "lets see how far we come" and - while I can imagine a lot of edge cases - I think with a good answer to this question we have like 95% of the puzzle solved and from there, we can start to think about how to "optionize" it (hopefully by then, we also have a nice settings view :) )

The 2nd problem for me with settings is, its a minor feature which a lot of people will not understand how to use. They go to settings to set up the filter and that is already complicated enough. They will understand a button in the spam folder and it would be intuitive for them. A checkbox on the settings page like "delete duplicate spam" (with a small description and a link to the wiki) which only pops up when you clicked "save spam in database" and once you have checked it a huge list of checkboxes and combinations pop up like "and, can you tell us, what is duplicate spam in your opinion?", so those people start to investigate what is actually duplicate spam and in the time doing so, they could have just deleted the spam. Some people like fine-tuning a car, most people just enjoy driving it.

**Comment by chesio** [comment]
I agree with @websupporter, let's keep it simple.

Just perhaps instead of (single) button that would require some inherent definition of what duplicate is, I would suggest slightly more cautious approach to begin with: an extra option under each item in Spam folder (in addition to "Kein Spam" and "Unwiderruflich löschen" options) that would say something along the lines of "Permanently delete including X duplicate comments", where X will be the number of duplicates. Obviously, this option would be appended only to spam comments that have at least one duplicate.

Advantage: We don't have to come with inherit definition of what duplicate is, because I believe 100% of users would expect that this option deletes all spam comments with the same content.

Disadvantage: One click is required per unique spammy comment.

**Comment by krafit** [comment]
I think, this whole feature is out of Antispam Bees scope. We should close the issue as "won't fix" :)
