### ISSUE TITLE
Hook that allows special kind of comment

### ISSUE THREAD

**Issue by kaffeeringe** [pluginkollektiv/antispam-bee#159]
Hi!

I use the comments as a simple event registration:
https://webmontag-kiel.de/event/webmontag-052017-diwokiel/

I removed the comment field and automatically fill it with the timestamp and a default text:

"Ich bin dabei! 09-23-20, 11-09-17, 2330 2320 1 Monpm17"

Antispam Bee filters these once in a while. I just saw the possiblity to add hooks to Antispam Bee. Can I write a hook that allows all comments that contain the text "Ich bin dabei!"? - How?

**Comment by websupporter** [comment]
Hi @kaffeeringe,
sorry for the very late reply.

Can you specify, what spam filter matches? How would your WordPress filter work? It would simply pass all comments with the text defined by the filter?

Like this?
```
$dont_check = apply_filters( 'good_name_goes_here', false, $all_the_comment_data)
```

Thanks for stepping in and helping out and sorry again, we didn't reply earlier.

**Comment by Zodiac1978** [comment]
Hey @kaffeeringe ,
do you have a solution already and can we close this issue? Or do you still need help?

**Comment by kaffeeringe** [comment]
Sorry for not answering. I'm not sure. I want to allow all comments that contain "Ich bin dabei!.*". Is the above filter the right place?

**Comment by Zodiac1978** [comment]
No, @kaffeeringe - there is no Hook available for this at the moment:
https://github.com/pluginkollektiv/antispam-bee/wiki/de-Hooks

@websupporter was trying to ask, if this is something that would work for you.

Although I am not sure if we should add such an filter to be honest ...

**Comment by kaffeeringe** [comment]
What speaks against such a filter?

**Comment by Zodiac1978** [comment]
> What speaks against such a filter?

It is an edge case and I don't see many use cases for it. But it could produce support questions. As we are just a bunch of volunteers I am trying to not waste our resources.

But I want to solve your problem :)

Another idea: Are these people already registered (even if just as "Subscriber") and would a setting help: "Trust all registered users"?

If not: why do these people got in the spam? What was the spam reason? Maybe you just need to optimize your settings?
https://torstenlandsiedel.de/2016/06/27/antispam-bee-richtig-konfigurieren/

**Comment by kaffeeringe** [comment]
They are not subscribers.
They are first time participants. I already set to trust known mail addresses.

**Comment by Zodiac1978** [comment]
Hi @kaffeeringe ,

there are just two options for trusting a comment at the moment. Gravatar and already commented, both can't be (mis-)used for your case because then ASB is de facto not used anymore (it would just check for empty fields, nothing more).

Even with the filter it would be no real solution. You can have ASB (then something is marked as spam as false positive from time to time) or you can have the filter which is used everytime because of your way of doing the registration and therefore disables ASB which would result in spam from time to time.

So if you want to have ASB *and* some sort of spam shield you need to "trick" the system but I can't help you with this, because I don't know the code of your solution.

**Comment by Zodiac1978** [comment]
Hey @kaffeeringe ,

maybe we are looking from the wrong side.

There is a filter in WP itself. Maybe you can use `pre_comment_approved` and check the commentdata content and set the approvement status to 1.

This should stop any further checks which could mark the comment as spam.
