### ISSUE TITLE
Inline JavaScript ab_script

### ISSUE THREAD

**Issue by shellshocker** [pluginkollektiv/antispam-bee#165]
Hello guys,

AntiSpamBee is adding some JavaScript to my site:
`<script type="text/javascript">document.getElementById("comment").setAttribute( "id", "f86b1a3e9808f48d5f0561002ac3f4ff" );document.getElementById("b6f09c8d9f").setAttribute( "id", "comment" );</script>`

I want to disable this, because I don't like JavaScript oder Inline JavaScript added to my site. I tried several things in functions.php - not working:

```
wp_dequeue_style('ab_script');
wp_deregister_style('ab_script');
wp_dequeue_script( 'ab_script' );
wp_deregister_script( 'ab_script' );
```

Different WordPress hooks:

```
add_action( 'wp_footer', 'remove_scripts', 100 );
add_action( 'wp_enqueue_scripts', 'remove_scripts', 100 );
add_action( 'plugins_loaded','remove_scripts', 100 );
```

Is it possible to get this out?

Best regards,
shellshocker

**Comment by websupporter** [comment]
Hi @shellshocker,
unfortunately not, this script is directly written into the HTML source: https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L1305

Its purpose:
Since we do some work on the `textarea#comment`, we wanted to make sure to give the correct commentfield its ID back, once the page is parsed, so in case people are styling the textarea using the ID, we wouldn’t break their styles.

**Comment by shellshocker** [comment]
Ok thanks @websupporter.
Is it possible to comment the line out or will this break anything important?

Maybe you should integrate an option to enable / disable the embed of JavaScript code. 

Best regards,
shellshocker

**Comment by shellshocker** [comment]
I commented the line for months now. It's okay. Maybe you integerate a switch in AntispamBee.
