### ISSUE TITLE
Handling min PHP Version

### ISSUE THREAD

**Issue by krafit** [pluginkollektiv/antispam-bee#216]
As @bueltge and @websupporter discussed in a thread somewhere here on GitHub, we have to raise the minimum required PHP version for Antispam Bee at some point. 

Lets discuss this process. As a starter I thought of a three-step process: 
1. display the currently minimum required PHP version on our w.org page
2. in the version _before_ we raise the minimum, we might add a notice for admins*
3. raise the minimum in the next major/minor version after the notice-update

* yes, this somewhat breaks the Pluginkollektiv tradition of NEVER EVER annoying users with admin notices, but I can't see another way of informing them, to update their dang servers.

**Comment by stklcode** [comment]
> yes, this somewhat breaks the Pluginkollektiv tradition of NEVER EVER annoying users with admin notices, but I can't see another way of informing them

I don‘t see any problem with raising a notice in case the current PHP version actually is below the targeted minimum, as this indicates a real issue. Notifying all users might indeed annnoye some.
The “risk” that someone downgrades PHP afterwards and has not be informed sounds acceptable to me.

**Comment by websupporter** [comment]
Probably, you already know, but for documentation purposes https://core.trac.wordpress.org/ticket/43987

To me the interesting question would be, what are the criteria on which we would say, yes an upgrade is necessary. The handling of such an upgrade as @krafit suggests looks like a good way to go, I agree with @stklcode on when to raise the notice and add:

If your PHP version is below the needed version, this admin notice will be displayed on `wp-admin/`. On the settings page of Antispam Bee I would suggest to display this notice regardless of the PHP version as a general information. Once the notice would be clicked away, it should hide forever.

Anyway, but these are details. Really interesting is the question: Why should we abandon 5.2?

We have our reasons as developers
- namespaces
- interfaces
- autoloader
- `declare(strict_types=1)`
- you name it

But how is this something which would improve the product for the user in the end?

Also raising the version, so we do not make the #208  "use `array()` instead of `[]`"-mistake again seems not sufficient to me.

As a developer, yes, lets go for PHP 7.2, but from the product perspective:
Give me the criteria which would make such a step necessary and improve the plugin in a way, we would say, yes its worth to abandon `unknown number` users.

**Comment by websupporter** [comment]
If we refactor the plugin (which I desperately hope for) and we have a more modular approach which would enable third party plugins to use single filters for e.g. ContactForm 7, other kinds of user submitted content etc., I think it would be a good thing to work at least with interfaces and stuff. This would be a criteria for me. It would not only be for lets say the "ASB"-core developers to have a nicer code, but would improve ASB. Not using interfaces there for me would be no good choice.

Additionally to the approach @krafit suggests, we might want to outbranch a 5.2-version for some time, which we want to feed with security updates if necessary. This way, people who are not able to update immediately could use the branch for some time to have at least a secure version of ASB.

This should be communicated well, also with an expiration date, so these users would be treated in a good way and not just simply abandoned.

**Comment by krafit** [comment]
> On the settings page of Antispam Bee I would suggest to display this notice regardless of the PHP version as a general information.
I wouldn't do that. As @stklcode stated, a PHP downgrade is extremely unlikely. It would be interesting to see, if the plugin could fail gracefully in such cases.

> Why should we abandon 5.2?
We should not abandon it for the sake of abandoning it. I started this issue to be prepared once we _have_ to raise it. The first possible / probable scenario for this is v3.0 – the rewrite @schlessera is working on.

> we might want to outbranch a 5.2-version
Yep, I also thought about a LTS version. Updating it might become a bit tricky, maybe we could use the GitHub updater – a second version of ASB in the .org directory

**Comment by chesio** [comment]
> On the settings page of Antispam Bee I would suggest to display this notice regardless of the PHP version as a general information.
I wouldn't do that. As @stklcode stated, a PHP downgrade is extremely unlikely. It would be interesting to see, if the plugin could fail gracefully in such cases.

The important thing is to keep main plugin file PHP 5.2 compatible and make a check in there for PHP version - see discussion/examples here: https://make.wordpress.org/plugins/2015/06/05/policy-on-php-versions/

This would mean that the `Antispam_Bee` class needs to be refactored into another file, but I think this should be done anyway as the main file should be slim.

Here's an example of PHP 5.4 compatible main plugin file for plugin requiring PHP 7.0: https://github.com/chesio/bc-cache/blob/develop/bc-cache.php :-)

**Comment by mundschenk-at** [comment]
You could use something like my library `[mundschenk-at/check-wp-requirements](https://github.com/mundschenk-at/check-wp-requirements/tree/1.0.x)` (the 1.0.x branch, `master` is PHP 5.6+ only). Contingent on how you want to handle dependencies, you can copy the source file (and the partial) or use it as a Composer dependency (should be fine without scoping because 1.0.x has been stable a long time and 2.x uses namespaces).

**Comment by krafit** [comment]
this discussion continues in #375
