### ISSUE TITLE
Delete IP hashes when plugin gets deactivated

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/antispam-bee#232]
Its good practice to clean up, when you leave a guest room. Currently, we do not clear the newly introduced hashed IP address when we leave the building. I suggest, we should do so with the next minor version.

:wastebasket:

**Comment by chesio** [comment]
It's quite possible that someone needs to deactivate Antispam Bee only for temporary period (testing plugin compatibility, doing maintenance etc.), so I would suggest to delete IP hashes on plugin **uninstall** instead of deactivation. As far as I can tell, this is also what [Plugin Handbook recommends](https://developer.wordpress.org/plugins/the-basics/uninstall-methods/).

**Comment by Zodiac1978** [comment]
Additionally we could add an option if the data should be deleted on uninstall. So you could delete a broken update (for example) without losing your data. Some plugins do this (Nina Forms for example)

**Comment by websupporter** [comment]
Actually, we have two meta keys, we could delete: The spam reason is also of no value and could be deleted.
