### ISSUE TITLE
New undetected Spam

### ISSUE THREAD

**Issue by wpgerd** [pluginkollektiv/antispam-bee#251]
In one of my sites, I have daily 10-15 comments with text "Mark Malvin" or "Steven Adler", which are not detected by Antispam Bee. They com from hunderets of different emails of @mail.ru.
![spamlog](https://user-images.githubusercontent.com/44336270/47265256-7e0baa00-d525-11e8-8856-54481d2acf99.JPG)
Thanks for help
Gerd

**Comment by florianbrinkmann** [comment]
I have the same issue.

**Comment by krafit** [comment]
Thank you both, and welcome to GitHub, @wpgerd 🎉 
We'll take a look at it.

**Comment by Zodiac1978** [comment]
@wpgerd @florianbrinkmann You can always use custom patterns for this:
https://gist.github.com/Zodiac1978/37dc557cd6873ba9e8590fb0a6ada8d0
https://torstenlandsiedel.de/2017/01/08/custom-pattern-fuer-antispam-bee/

I think we can't add mail.ru or gmail.com to the official blacklist and adding a name seems to be overkill here too. But if you want to stop a temporary spam wave with this you can add this locally.

**Comment by krafit** [comment]
as @Zodiac1978 already mentioned, there is no really good way for us to tackle this kind of spam other than blocking mail.ru (which is a genuine mail provider). But there is some work done in order to give you the option to take care of this on a per instance level. see #259 

So for now, this is a *wontfix*.
