### ISSUE TITLE
Error 500 when installed on v3 of wordpress

### ISSUE THREAD

**Issue by moisesgarcia** [pluginkollektiv/antispam-bee#256]
By mistake, I installed this plugin in a wordpress version 3.5 and all pages now throw an error 500 and I cannot remove the pluging. How can I remove manually the plugin?

**Comment by stklcode** [comment]
You can simply delete the `wp-content/plugins/antispam-bee` directory.

Database options probably have not been stored yet due to the error (and they wouldn't do any harm anyway), but to be sure you might remove the options from your database manually. Either by some options management plugin or via SQL:
```sql
DELETE FROM `wp_options` WHERE `option_name` = 'antispam_bee'
```

**Comment by moisesgarcia** [comment]
Thanks @stklcode !! Worked like a charm
