### ISSUE TITLE
Checking local spam database exceeds memory limit

### ISSUE THREAD

**Issue by felixarntz** [pluginkollektiv/antispam-bee#258]
I noticed that comments on my site weren't working for new email addresses. When investigating I found out that this is caused by Antispam Bee looking up all comment meta keys `antispam_bee_iphash` for comments that have been marked as spam. It then calls `wp_check_password()` for every result.

Since the amount of spam can grow large over time, this was causing my memory limit of 30 seconds to be exceeded. I fixed this by disabling the DB spam lookup option for now, but I wonder whether there might be a more performant way of handling this.

Note that I'm using https://github.com/roots/wp-password-bcrypt on my website, which is overriding WordPress's default password functions - I don't think that's related though, it appears to me that it's simply the large amount that the `wp_check_password()` function is called.

**Comment by schlessera** [comment]
@websupporter I would recommend changing the approach for this check completely, the current behavior is not scalable.

First of all, there does not seem to be a need afaict to store the IP address with the spam comment. If a comment is detected as being spam, I would fetch its IP address and then store it in a separate data store that only contains "IPs known to be spammy". There will be no tie back to the source comment, so this should get rid of the GDPR issue.

Then I would store these IPs in a separate table so that a very fast indexed query can return whether there's a match or not.

**Comment by websupporter** [comment]
This sounds good @schlessera,
only thing I would add is, if we only do this for comments which are already catched as spam by us, there is no much use for this check at all. If we do it for all comments and a spam-comment slips through our tests, a manual marking of this comment as spam would block this IP. I think this is the strength of the check.

Reminder, there is a IP column in the wp_comments table. It is not indexed but before the change we basically used this column and it did prove stable. We changed it during GDPR because of this core ticket: https://core.trac.wordpress.org/ticket/43588

Maybe we should just change back and see how this ticket will evolve in the future before we take specific action.

**Comment by websupporter** [comment]
:thinking: 
A possibility would be as the Ticket mentions to delete IPs once the comment leaves the "pending" status, we could listen to this move and if this move is towards spam we could store the IP in our seperate table.

For such a table, I would like to have feedback of people, who are more knowledgeable about GDPR than I am.

**Comment by websupporter** [comment]
> There will be no tie back to the source comment

**Comment by websupporter** [comment]
> There will be no tie back to the source comment

If we do not have a connection between comment and IP and a false positive and the admin moves the comment out of spam, the IP will still be blocked.

**Comment by websupporter** [comment]
I've spoke with a person knowledgeable of GDPR. We could basically without a problem save the IP together with the comment ID for a reasonable time frame. So this would be a way to go.

Nevertheless, for now, I would just go with the IP we have in the `wp_comments`. I am going to prepare a patch for that. Should the core behaviour change, we can still revisit this issue and decide on the solution.

Greetings from #wcthess2018
