### ISSUE TITLE
Fake IP test produces false positives

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#27]
I don't know if the fake IP check is working in every situation. See this support thread:
https://wordpress.org/support/topic/fake-ip-problem

User can easily disable it, but maybe we should discuss the feature.

**Comment by swissspidy** [comment]
As discussed internally last month, the fake IP check isn't 100% reliable nowadays due to the way servers are setup. We should think about removing this check.

Possible routes:

1. Remove check completely. It's unreliable and probably doesn't catch that much real spam.
2. Do not enable by default for new sites and improve wording ("Validate the ip address of commenters" isn't really clear about what this does).

I'm for 1) though as I rather have a plugin with reliable filters instead of one causing plenty of false positives.

**Comment by swissspidy** [comment]
See also #19.
