### ISSUE TITLE
Google+ shutdown in April breaks some links

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#274]
For example this: https://plus.google.com/+SergejM%C3%BCller/posts/dZmhFZTMTjh

https://github.com/pluginkollektiv/antispam-bee/wiki/de-Dokumentation#tipps--tricks
https://github.com/pluginkollektiv/antispam-bee/wiki/en-Documentation#tips--tricks

Are there more links? How to solve this issue? Move this to the wiki or just adding a link to
http://torstenlandsiedel.de/2016/06/27/antispam-bee-richtig-konfigurieren/
or
https://www.perun.net/2016/08/30/antispam-bee-in-wordpress-richtig-konfigurieren-um-spam-zu-minimieren/
or both?

**Comment by krafit** [comment]
Really good catch. We might want to check all our wikis for links like these. I‘d prefer to move the relevant content directly to the wiki, so we can make sure, everything stays available and up to date.

I‘d also propose a Documentation-Team at our next Hackathon, since our goal is, to move documentation away from GitHub, we might do all of this in one step (the Hackathon will take place a couple of weeks befor Google shuts down G+).

**Comment by Zodiac1978** [comment]
The mentioned post is now updated on de+en in our wiki.

But what about this link to Google about the language detection?
https://github.com/pluginkollektiv/antispam-bee/wiki/de-Hooks#ab_get_allowed_translate_languages

Which of the packages are we using?
https://github.com/wooorm/franc

Ping @krafit @websupporter

**Comment by krafit** [comment]
Fixed in #328
