### ISSUE TITLE
autocomplete="nope" breaks html validation - may not work anymore anyway?

### ISSUE THREAD

**Issue by oldrup** [pluginkollektiv/antispam-bee#280]
Problem: The autocomplete="nope" workaround, for the issue that Chrome ignores autocomplete="off", has the unfortunate side effect, that it throws an error in w3c.org's html validation service.

While you and I know that it is probably safe to ignore that error message, teaching co-workers to "just ignore errors" is a road its maybe not wise to go down :)

Furthermore, there are rumours that "... it seems the latest version of Chrome is ignoring autocomplete attribute regardless of what your using nope or `off."
https://github.com/algolia/autocomplete.js/issues/247#issuecomment-444133128

And oh boy there are many creative (and ugly) workarounds involving jquery and whatnot :o

The most sensible solution I saw, was creating a unique random name for the field, and it seems that Antispam Bee already does that?

Another suggested setting the value attribute to a blank space, as chrome shouldn't fill out fields that already contains a value. Arguments that, that isn't a very pretty approach,forcing the user to remove a space before entering content, may not apply to a hidden honeypot field filled out by bots anyway?

If autocomplete="nope" is essential for Antispam Bee to work, last resort could be a note/warning in the backend, that this particular html validation error can and should be ignored as it's a required part of the antispam-mechanism by design.

On my personal blog, I changed the autocomplete="nope" to "off" for a succesful validation. Commenting still works. I'll monitor it over the next weeks to see if the change affects my spam amount.

Kind regards
Bjarne

**Comment by Zodiac1978** [comment]
Related #142

**Comment by 2ndkauboy** [comment]
If `nope` really doesn't work anymore, we could switch to `off` or remove it completely.

If it's still the only solution, it should stay. But I would at most add something to the plugin's FAQ section and not to the backend. Only very few people validate their pages and it would confuse (or even scare) too many others.

**Comment by Zodiac1978** [comment]
The `nope` comes from this page:
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

But the text (quoted on #142) is not there anymore. No recommending to use `nope`.

But it is mentioned, that `off` will be ignored on login forms, which should be okay for us, because we just use it (at the moment) in the comment area.

So I would think we can use `off` again, or at least we should test this. 

Another workaround is mentioned on this page. We could use `new-password`, which should tell the browser, that this is for a new password and autofill is therefore not useful here.

Personally I would prefer to go back to `off` again, which would solve the validation problem too. 

The only problem could be, that older version of Chrome could have a problem. But as Chrome is auto-updating itself, this shouldn't be a big problem. What do the other think? @websupporter or @schlessera ?

**Comment by websupporter** [comment]
For more context:
Related is also #130. This is where the autocomplete was introduced because it was reported that the comment field got populated with the street name. We switched to `autocomplete=off` to tell browsers to not autocomplete. Unfortunatly, Chrome didn't care, but it acted on `nope` which was the suggested workaround on MDN at that time.

If Chrome decides now to ignore autocomplete completely, I strongly hope, they have a better logic implemented on what fields to populate.

I will have a closer look these days. Thank you @oldrup for bringing this up.

**Comment by websupporter** [comment]
I used this simple form with Chrome 74, 75, 76beta:
```
<!doctype html>
<html>
	<head>
	</head>
	<body>

		<form method="post" action="http://localhost/test.html">
			<p>
				<label for="name">
					Name
				</label>
				<input id="name" name="name">
			</p>

			<p>
				<label for="street">
					Street
				</label>
				<input id="street" autocomplete="off" name="street">
			</p>

			<p>
				<label for="postal-code">
					ZIP Code
				</label>
				<input id="postal-code" name="postal-code">
			</p>
		</form>
	</body>
</html>
```
`off` did not work. `nope` did still work. `no` seems to work as well, but then again, this is not a valid attribute according to W3C validator.

> Another suggested setting the value attribute to a blank space, as chrome shouldn't fill out fields that already contains a value.
I tested that, but Chrome overwrote it in my tests. Actually, its also not a solution for our use case as bots usually do not fill fields, which are already filled, so basically our honeypot would loose its functionality.

It bugs my quite a lot that we do not have a valid markup currently, but it seems currently this `nope` is the only safeguard we have against some strange behavior of Chrome (when it basically seems to put the street name into the comment area for reasons i can not really understand or reproduce but I remember Twitter).

So, currently, I have no real way forward here until Chrome... :face_with_head_bandage:

**Comment by Zodiac1978** [comment]
@websupporter Any chance to test `new-password` with Chrome?

@schlessera How about your research? New insights how to solve this?

**Comment by chesio** [comment]
It seems the `new-password` is the only working workaround for Chrome in the moment, at least according to a lengthy discussion here: https://bugs.chromium.org/p/chromium/issues/detail?id=914451

**Comment by Zodiac1978** [comment]
One more advantage: `new-password` validates as correct HTML markup.
