### ISSUE TITLE
AMP compatibility

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#283]
> it injects custom scripts which not amp compatible and added a style that has “!important” which cause an error too.
> 
> Errors:
> 1.The attribute ‘style’ in tag ‘textarea’ is set to the invalid value ‘padding:0;clip:rect(1px, 1px, 1px, 1px);position:absolute !important;white-space:nowrap;height:1px;width:1px;overflow:hidden;’
> 
> 2. Custom JavaScript is not allowed
> 
> PS: when I disable the antispam bee plugin. those two errors will be resolved.
> You can validate the page above by copying the source code via page source and paste it in https://validator.ampproject.org/

From: https://wordpress.org/support/topic/not-compatible-in-amp/

Any ideas @schlessera @websupporter ?

**Comment by websupporter** [comment]
I just tried amp in the different modi the official amp plugin provides. To me currently it seems, the plugin takes care about this for us. My first uneducated guess is: if you create an amp page without the plugin, you would run into those problems. The amp plugin for example just gets rid of the inline style and adds the declaration as a new class. The Javascript `<script>` is just kicked out, so the IDs of the textarea do not get swapped, which doesnt hurt too much.

I think the first action item would be: be more precise, when we talk about amp compatibility in the change log and instead claim to be "compatible with the official amp plugin".

Maybe it would be an interesting thought, whether we want to get rid of the inline style and the script. For the style, we could hook into `wp_head` and print it. For the amp plugin we would need hook into `amp_post_template_css` i think.

For the Javascript part we would need to evaluate how important it is. Our comment textarea does not have the ID to remove another indicator for bots. Since there might be styles relying on `#comment` we add it back afterwards again. Maybe we could give it a shot and silently just remove the script.

**Comment by westonruter** [comment]
Hello! This just came up this week in the AMP plugin: https://github.com/ampproject/amp-wp/issues/3415. 

This is the problematic code being introduced by Antispam Bee:

https://github.com/pluginkollektiv/antispam-bee/blob/e91ea009268516908d6d2242cb31be98aee1aa27/antispam_bee.php#L1200-L1204

The issue is compounded in the AMP plugin because the validation error being caused by Antispam Bee gets detected when rendering the page, but it is not detected when doing a validation request to determine the sources of the validation errors. This is due to how the output buffering in Antispam Bee is conflicting with how the AMP plugin is using output buffering to annotate markup for tracing sources. See https://github.com/ampproject/amp-wp/issues/3415#issuecomment-537608833.

Akismet was made AMP-compatible by just skipping outputting the JS in AMP responses: https://plugins.trac.wordpress.org/changeset/2086419/akismet

Could the same be done for Antispam Bee?

**Comment by websupporter** [comment]
We should take care of this in the next release. Somehow this slipped through.
