### ISSUE TITLE
readme.txt still says min wp version is 3.8

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/antispam-bee#309]
https://github.com/pluginkollektiv/antispam-bee/blob/master/readme.txt#L54

should be 4.5 as stated here
https://github.com/pluginkollektiv/antispam-bee/blob/master/readme.txt#L5

**Comment by Zodiac1978** [comment]
I have checked the master branch with https://wpseek.com/pluginfilecheck/ and got WordPress 4.4.0 as required version (because of wp_parse_url) - why do we require 4.5?

According to https://github.com/pluginkollektiv/antispam-bee/pull/85#issuecomment-393671589 this was an accident. Just documenting here, for future reference. :)
