### ISSUE TITLE
BBCode check is just looking for Links

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#320]
Our setting "BBCode is spam" is suggesting that we will check for *all* BBCode.
https://github.com/pluginkollektiv/antispam-bee/wiki/en-Documentation#bbcode-is-spam

But in fact we are just checking for the URL BBCode:
https://github.com/pluginkollektiv/antispam-bee/blob/1ba9929b388de6b253ea5cc6046ecf38ec4cbe38/antispam_bee.php#L1759

There are some more: https://en.wikipedia.org/wiki/BBCode

**Comment by websupporter** [comment]
I haven't seen a lot of BBCode used in Spamcomments since quite a while. But what I remember: Spamcomments where eager to place urls using BBCode. Therefore the url check seems sufficient to me.

In terms of documentation:
* Does a more detailed explanation help to decide whether to activate or deactivate this feature?
* Did we get complaints like "Hey why did [b]some spam[/b]" slip through?

These would be the criteria to me to make a change here.

**Comment by Zodiac1978** [comment]
I think it is more a matter of documentation. Let us be clear what we do exactly.

**Comment by websupporter** [comment]
I had a look on it:

In the settings its clearly mentioned we are checking for bbcode links:
![image](https://user-images.githubusercontent.com/6458412/79609319-35738380-80ff-11ea-8e89-6e7c71033da3.png)

In the wiki it states:

> When activated, Antispam Bee checks incoming comments for the existence of BBCode links. 

Imho its sufficient.

**Comment by Zodiac1978** [comment]
I am suggesting to change the title from "BBCode is spam" to "BBCode links are spam" (or similar).
