### ISSUE TITLE
WPTouch compatibility

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#331]
I stumbled upon the function `_is_mobile`:

https://github.com/pluginkollektiv/antispam-bee/blob/4252eee0c6d222ff295b86a2d71399f80e976846/antispam_bee.php#L2174-L2184

It seems is just used to check for the usage of [WPTouch](https://de.wordpress.org/plugins/wptouch/)

We exit early if this is true:
https://github.com/pluginkollektiv/antispam-bee/blob/4252eee0c6d222ff295b86a2d71399f80e976846/antispam_bee.php#L1050
and
https://github.com/pluginkollektiv/antispam-bee/blob/4252eee0c6d222ff295b86a2d71399f80e976846/antispam_bee.php#L1137

But I am not sure why.

At least the pro version is having a comment section:
https://support.wptouch.com/article/1410-cms-theme-settings

Do they change the comment form and therefore are not compatible with us? Has anyone more info on this?

**Comment by krafit** [comment]
I'm really stunned. WPTouch is still thing 😳

I recall a problem with their comment form, but it's at least 7 years since I used it myself.

**Comment by websupporter** [comment]
To me it looks more like, let's deprecate wptouch support. I hope I dont stumple at someones feet when I say, this plugin has probably run its course. Was great back than though.

**Comment by krafit** [comment]
Agreed, let's drop WPTouch support

**Comment by Zodiac1978** [comment]
The free plugin has two themes and one is using the default comment form and the other is using a custom form, but both are working with our RegEx replacement.

So I think this shouldn't be necessary anymore and I'm wondering why this was added in the first place.

**Comment by websupporter** [comment]
If we can't hook into a comment form to do our replacement, we are not compatible due to 
https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L1048-L1072
and 
https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L1406

Currently we need our $_POST fields to be populated to work correctly, therefore our plugin can not work if the honeypot can not work.

I checked it now by activating wptouch and altering our code
```
	private static function _is_mobile() {
+	    return false;
-		return strpos( get_template_directory(), 'wptouch' );
	}
```

and i ended up in the honeypot. So currently this method insures "compatibility"

**Comment by Zodiac1978** [comment]
> If we can't hook into a comment form to do our replacement, we are not compatible

Okay, I do not thought about that, was just looking at the markup and if it matches with our RegEx.

Then I would vote for keeping it (at least until v3 maybe longer) and therefore close this ticket. Okay?
