### ISSUE TITLE
Notice: Undefined index: server

### ISSUE THREAD

**Issue by KittMedia** [pluginkollektiv/antispam-bee#334]
Hey,

in version 2.9.2, I got the following error message once on the edit comments page (`/wp-admin/edit-comments.php`):

```
ErrorException: Notice: Undefined index: server
#7 /wp-content/plugins/antispam-bee/inc/columns.class.php(112): Antispam_Bee_Columns::filter_columns
#6 /wp-includes/class-wp-hook.php(287): WP_Hook::apply_filters
#5 /wp-includes/class-wp-hook.php(311): WP_Hook::do_action
#4 /wp-includes/plugin.php(478): do_action
#3 /wp-admin/includes/class-wp-comments-list-table.php(411): WP_Comments_List_Table::extra_tablenav
#2 /wp-admin/includes/class-wp-list-table.php(1248): WP_List_Table::display_tablenav
#1 /wp-admin/includes/class-wp-comments-list-table.php(501): WP_Comments_List_Table::display
#0 /wp-admin/edit-comments.php(345): null
```

By accessing the page again, there is no new error event.

**Comment by websupporter** [comment]
Thanks for your report @KittMedia, I will have a look into it quickly.

**Comment by Zodiac1978** [comment]
I think this is because of https://github.com/pluginkollektiv/antispam-bee/pull/321/commits/a14bbe3f5c630a97c541b5f6c93dcf5ca7c6c1e4 - we removed the fake IP check but there are still entries in the DB which are displayed but the reason is not in the `_init_internal_vars` array anymore.

We need to re-add this line.
