### ISSUE TITLE
Drop support for old PHP versions

### ISSUE THREAD

**Issue by krafit** [pluginkollektiv/antispam-bee#375]
During our weekly chat this week we realized, Antispam Bee still officially supports PHP versions all the way down to `5.2`. 
Since testing against older PHP versions as well as supporting both 5.2 and 8.0 won't be realistically possible for us, we should move along and drop official support for older PHP versions.

I'd like to propose a rather simple path:

1. raise min. PHP version right away, add explanation to the README (and subsequently to our w.org page)
2.  include an admin notice in the next update, informing everyone with an unsupported version about way to update their PHP

Back in 2018 when I wrote about this for the first time (#216), my plan for moving forward was way more complicated. I don't think, we need to be as careful as back in 2018 anymore. WordPress moved an and so should we.

**Comment by mundschenk-at** [comment]
If you want to 5.6 as the minimal PHP version, I'd suggest also raising the required WordPress version to 5.2 to prevent possible problems with manual installations.

**Comment by Zodiac1978** [comment]
@mundschenk-at WordPress supports PHP 5.6 since version 4.1, so which manual installation do you see here? On installation <4.1?
https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/

**Comment by mundschenk-at** [comment]
> @mundschenk-at WordPress supports PHP 5.6 since version 4.1, so which manual installation do you see here? On installation <4.1?
> https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/

But only WordPress 5.2 **requires** PHP 5.6, and plugin PHP requirements are only enforced by Core since WordPress 5.1 (but you could still break things by manually installing a plugin).

**Comment by 2ndkauboy** [comment]
>but you could still break things by manually installing a plugin

@mundschenk-at this can very easily be prevented with a `version_compare` check at the top of the plugin file.

**Comment by Zodiac1978** [comment]
So if you install ASB manually (e.g. via FTP) on WP 4.5+ (required from ASB) and <5.1 we could break the installation if we are using PHP which is not compatible with PHP lower than 5.6 but the server is using PHP lower than 5.6?

Seems not very likely that this happens IMHO.

But we could add a check in the main plugin file to check for any requirements for this extra safety, like @2ndkauboy mentioned. Not needed to raise the required WP version.

**Comment by mundschenk-at** [comment]
No, if your WordPress version requirement is less than 5.1, you can install the plugin via the normal web UI and break things.

Only one version (WP 5.1) will prevent normal installation and only break when you install the plugin manually (by dropping it in `wp-content/plugins`). Since as of WP 5.2, WordPress itself needs at least PHP 5.6, my suggestion was starting with that as the minimum version, because IMHO supporting 5.1 is not worth the potential hassle (support requests).

If you still want to support anything earlier than 5.1, you have to handle things gracefully because WordPress will happily ignore your stated PHP version requirements. I do have a solution for that that I've been using in my plugins for years ([mundchenk-at/wp-requirements](https://github.com/mundschenk-at/check-wp-requirements/tree/1.0.x)), but this means that your "bootstrap" files (the main plugin file and any uninstall handler or `uninstall.php`) need to be PHP 5.2 only (`version_compare` by itself is not a sufficient guard for any constructs that are not valid PHP 5.2, because they will break the parser).

**Comment by mundschenk-at** [comment]
(Also to be nice, you should inform the user what is going wrong, and not simply do nothing on activation. The library I linked does that, BTW.)

**Comment by 2ndkauboy** [comment]
> but this means that your "bootstrap" files (the main plugin file and any uninstall handler or uninstall.php) need to be PHP 5.2 only

Sure the main file would then have to be PHP 5.2 code only.

**Comment by Zodiac1978** [comment]
We do not want to cut off 25% from further updates, so we do not want to raise the *required* WP version. And we are aware that WP does this only from 5.2 for us, so we will check this (if needed - at the moment we do not use code that is not running in PHP <=5.2)

Thanks for your class. I had a simpler solution like https://pento.net/2014/02/18/dont-let-your-plugin-be-activated-on-incompatible-sites/ in mind, but the solution are comparable.

Thanks for the heads up!
