### ISSUE TITLE
Raise required WordPress and PHP version

### ISSUE THREAD

**Issue by pfefferle** [pluginkollektiv/antispam-bee#435]
WordPress needs at least PHP version 5.6.20+ (but recommends 7.4), so I would recommend to raise the required PHP version of Antispam-Bee to 5.6 (and the required WordPress version accordingly).

-- https://wordpress.org/about/requirements/

**Comment by Zodiac1978** [comment]
Related: https://github.com/pluginkollektiv/antispam-bee/issues/375

**Comment by NicoHood** [comment]
Is it safe to upgrade, or do you see any issues or blocking points? Cause then I would upgrade earlier than the number in the readme/wordpress.org is updated. Thanks :)

**Comment by krafit** [comment]
@NicoHood I wouldn't worry. I've tested Antispam Bee with WordPress 5.9 (and the RC versions) for weeks without any issues.

**Comment by Zodiac1978** [comment]
After discussion in team meeting this is punted until there is a function need (from WP or PHP) which is not available for us with the actual supported versions.

This decision could be revised anytime (especially because the testing infrastructure gets more complicated with more new versions). If the testing tools do not support the old version this could lead to raising this version numbers.

**Comment by florianbrinkmann** [comment]
After discussion we decided to use PHP 7.0 as the min PHP version for ASB 3 and WordPress 5 as the min required WordPress version

**Comment by Zodiac1978** [comment]
There is no actionable item here and a path forward for v3, so I close this issue.
