### ISSUE TITLE
ASB Ajax call for email marketing integration.  

### ISSUE THREAD

**Issue by TNHSAesop** [pluginkollektiv/antispam-bee#504]
Hi there, 

I'm having issues with my CRM integration not working properly and I tracked it back to Anti Spam bee blocking AJAX calls.  I have added the following code to my functions.php file but am still getting 403 errors.

`add_filter( 'antispam_bee_disallow_ajax_calls', '__return_false' );`

When I disabled ASB the integration works successfully.  The documentation for this is confusing/too sparse.  How can I allow ajax calls?  Or better yet how can I whitelist specific Ajax calls?

https://antispambee.pluginkollektiv.org/documentation/#antispam_bee_disallow_ajax_calls

**Comment by Zodiac1978** [comment]
Hi @TNHSAesop 

this is an interesting question, but you gave not many details we could use to debug.

Which CRM are you using? Which request gets the 403 error exactly?

First, I looked in our code when we are returning a 403 status and found only one occurrence:
https://github.com/pluginkollektiv/antispam-bee/blob/e3772aa83d59029a69b5c4a4ce52d7e1de56f649/antispam_bee.php#L2416

This only happens if we delete spam, so we have 3 times we do this:
* if the setting is used to not mark as spam, but delete the comment directly
* if the type is pingback/trackback and you have set up to ignore this type of comment
* if the spam reason is set up to be deleted immediately 

Can you please check your settings if something is set up this way in your case?

Please report back if this is not the case with all active plugins, your theme and your server environment. You can use the Health Check plugin to generate a copy&paste list of all this data. Thanks in advance!

All the best
Torsten

**Comment by TNHSAesop** [comment]
Hey @Zodiac1978 I don't think the plugin itself is returning the 403 error but rather categorically blocking calls to admin-ajax.php (which is how a lot of spammers make comments by botting out comments via ajax calls). The 403 error is independently generated as a result of that.  I have many landing pages and on-page subscribe widgets sprinkled throughout my site that capture an email address and then push the email via an Ajax call to the backend of WordPress where it's then pushed to the CRM.  Example page: https://tortoiseandharesoftware.com/offers/msp-lead-value-estimation-spreadsheet/

Please note that I have uninstalled ASB on this website and put a different solution in, but have ASB installed on half a dozen of my client's sites (but they don't have CRM integrations on their sites, so it's not an issue yet).

**Comment by Zodiac1978** [comment]
I can't help you, if you don't answer my questions @TNHSAesop 

We exit our init function if it is an AJAX request, because most times comments are not submitted via AJAX:

https://github.com/pluginkollektiv/antispam-bee/blob/e3772aa83d59029a69b5c4a4ce52d7e1de56f649/antispam_bee.php#L142-L146

That is the only thing we do with AJAX calls.

How is your CRM integrated in the (comment) form? What are your ASB settings?

If you can't provide more details about your environment and steps needed to reproduce this issue, I'm afraid we can't help you.

**Comment by TNHSAesop** [comment]
Hey @Zodiac1978 I don't know I had uninstalled the plugin and had the "delete data" option checked.  I tried re-installing it and checking the settings you mentioned but can't reproduce the issue anymore.  I guess you can close this issue for now, I'll re-open if I spot it again :-/
