### ISSUE TITLE
Notice: Function _load_textdomain_just_in_time was called incorrectly

### ISSUE THREAD

**Issue by oldrup** [pluginkollektiv/antispam-bee#625]
**Describe the bug**

_Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the antispam-bee domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see Debugging in WordPress for more information. (This message was added in version 6.7.0.) in /home/mkjqekzy/public_html/wp-includes/functions.php on line 6099_

**To Reproduce**

1. Install WordPress beta tester plugin
2. Update to WordPress 6.7 beta 3
3. Enable WP_DEBUG
4. Enable AntiSpam Bee

**Expected behavior**
It looks like a deprecation warning of some sort. Not that unexpected really ;)

**System (please complete the following information):**
- WordPress 6.7 beta 3
- Firefox browser
- PHP 8.2.x

**Additional context**
![image](https://github.com/user-attachments/assets/cde58abc-331c-4524-b100-8a671fcd5336)

**Comment by Zodiac1978** [comment]
Thanks for the report @oldrup !

I hoped this was already fixed: https://github.com/pluginkollektiv/antispam-bee/issues/423

We will have a look why this happens again ...

**Comment by Zodiac1978** [comment]
Maybe this is because we load the textdomain here in the "init" function:
https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L155

Which is on the "plugins_loaded" hook:
https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L2987-L2994

But the documentation is not clear about which hook is correct:
https://developer.wordpress.org/reference/functions/load_plugin_textdomain/

**Comment by oldrup** [comment]
Well, keep in mind I encountered this warning with WordPress 6.7 **beta 3**. A lot might still change, and this can also be an issue with core, I just wanted to bring it to your attention. AntiSpam Bee still filters just fine, so no cheap viagra for me, I suppose 🙄

**Comment by 2ndkauboy** [comment]
This is probably related to this change: https://core.trac.wordpress.org/ticket/44937

We have to take another look at this.

**Comment by Zodiac1978** [comment]
Yes, @luminuu was posting this ticket on X/Twitter too.

Looks like this could be the second call here:
https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L2556

This is called on the `comment_post` action hook, which could be the problematic trigger here.

**Comment by 2ndkauboy** [comment]
But that wouldn't trigger when navigating to the Dashboard, right?

I can debug this locally with XDebug and 6.7 beta 3 later.

**Comment by Zodiac1978** [comment]
> But that wouldn't trigger when navigating to the Dashboard, right?

If this is not the problem, we maybe should change `plugins_loaded` to `init` - as this is mentioned here:
https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain

The docs for load_plugin_textdomain are not clear here, but the example clearly says `init`.

**Comment by Zodiac1978** [comment]
@swissspidy was suggesting on X/Twitter to get rid of the load_plugin_textdomain completely. This would need WP 4.6, so we need to raise the version from 4.5 to 4.6:

https://make.wordpress.org/core/2016/07/06/i18n-improvements-in-4-6/

https://github.com/pluginkollektiv/antispam-bee/blob/master/readme.txt#L5

**Comment by swissspidy** [comment]
Tip: Query Monitor is very helpful to see the stack trace of how such warnings are triggered.

For Antispam Bee, it looks as follows:

In WordPress 6.6 and below:

`plugins_loaded` -> `Antispam_Bee::init()` -> `Antispam_Bee::load_plugin_lang()` -> calls `load_plugin_textdomain()` and thus triggers translation loading.

In WordPress 6.7, `load_plugin_textdomain()` was changed slightly to defer translation loading until they are really needed, reducing the chance for getting those new doing_it_wrong warnings. However, for Antispam Bee, nothing really changes, just the order is slightly different.

In WordPress 6.7:

`plugins_loaded` -> `Antispam_Bee::init()` -> `Antispam_Bee::add_reasons_to_defaults()` -> calls `esc_attr__()` and thus triggers translation loading.

The easiest fix would be to call `Antispam_Bee::init()` on `init` instead of `plugins_loaded`. You will have to check whether that works for you and all tests still pass etc.

Alternatively, you could probably remove the `self::add_reasons_to_defaults();` call to within the `_init_internal_vars()` method. Though `add_reasons_to_defaults()` mentions it's separate for some reason, so you will have to test that.

Either solution will resolve the new warnings though.

(And yes, if you bump your WP version requirement, you can totally remove the `load_plugin_textdomain()` call)

**Comment by 2ndkauboy** [comment]
@swissspidy thanks for the explanation! I was also able to reproduce this with Xdebug locally.

Can you please take a look at the PR? This should resolve it. At least, I don't see any notice locally anymore.

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by oldrup** [comment]
> @swissspidy was suggesting on X/Twitter to get rid of the `load_plugin_textdomain` completely. _This would need WP 4.6, so we need to raise the version from 4.5 to 4.6:_

Out of curiosity. When having a plugin published on WordPress.org. Are there any statistics available to the maintainers, whether there are AntispamBee users running WP 4.5? And who is actively moderating comments, if I may add? A website that hasn't been updated for 8 years sounds abandoned to me. But apparently they do exist? 🤷‍♂️

![image](https://github.com/user-attachments/assets/a65f77c8-a3a7-40aa-8f88-02026b932b41)

**Comment by oldrup** [comment]
A week ago, Pascal Birchler posted this article on WordPress.org, addressing the warnings. It might be useful. I get this warning on around a quarter of the plugins I regularly use, including widely used ones as UpdraftPlus.

https://make.wordpress.org/core/2024/10/21/i18n-improvements-6-7/

_Fun fact, since I disabled AntiSpam Bee on my test site (not to be distracted by the warning), I've seen a lot more engagement on my blog posts, more than 300 comments! Nice. Unfortunately, they are mostly in Russian, so I don't quite understand them, but cool! 😉_

**Comment by 2ndkauboy** [comment]
@oldrup thanks again for the reminder on the WordPress version! I'll change the "Requires at least" to 4.6 now as well.

I also don't think it's an issue. Anyone trying to update to the new version, who still uses WordPress 4.5, would get a warning that they can't update, right? Unless that check was also only implemented later. :thinking: 

But I also think that most sites with such an old WordPress version are not maintained anymore.

So, any objections on merging it?
